// <auto-generated />
using System;
using Ciandt.Retail.MCP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ciandt.Retail.MCP.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    partial class RetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(791),
                            CustomerId = 1,
                            IsDefault = true,
                            State = "NY",
                            Street = "123 Main St",
                            ZipCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(794),
                            CustomerId = 2,
                            IsDefault = true,
                            State = "CA",
                            Street = "456 Broadway",
                            ZipCode = "67890"
                        },
                        new
                        {
                            Id = 3,
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(795),
                            CustomerId = 2,
                            IsDefault = false,
                            State = "CA",
                            Street = "789 Park Ave",
                            ZipCode = "67891"
                        });
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CartEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CartItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CouponEntity", b =>
                {
                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentUses")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinimumPurchaseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponCode");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentCPF")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(768),
                            DocumentCPF = "",
                            Email = "marcio.nizzola@ciandt.com",
                            Gender = "",
                            Name = "Marcio Nizzola",
                            Phone = "5511984701979",
                            Zip = "13.328-283"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(770),
                            DocumentCPF = "",
                            Email = "ricardoso@ciandt.com",
                            Gender = "",
                            Name = "Ricardo Odorczyk",
                            Phone = "5541999089809",
                            Zip = "67890"
                        });
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.PaymentEntity", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("InstallmentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableColors")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvailableSizes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasPromotion")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromoLabel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableColors = "[\"Preto\",\"Branco\"]",
                            AverageRating = 4.7000000000000002,
                            Brand = "TechConnect",
                            Category = "Roteadores",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(613),
                            DiscountedPrice = 249.99m,
                            HasPromotion = true,
                            ImageUrl = "roteador1.jpg",
                            InStock = true,
                            IsBestSeller = true,
                            IsNew = false,
                            Name = "Roteador NetSpeed 500 Dual Band",
                            Price = 299.99m,
                            PromoLabel = "Oferta da Semana",
                            ReviewCount = 1258
                        },
                        new
                        {
                            Id = 2,
                            AvailableColors = "[\"Preto\"]",
                            AverageRating = 4.9000000000000004,
                            Brand = "NetMaster",
                            Category = "Roteadores",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(615),
                            HasPromotion = false,
                            ImageUrl = "https://example.com/images/router-ultraconnect-wifi6.jpg",
                            InStock = true,
                            IsBestSeller = false,
                            IsNew = true,
                            Name = "Roteador UltraConnect WiFi 6 Mesh",
                            Price = 599.99m,
                            ReviewCount = 358
                        },
                        new
                        {
                            Id = 3,
                            AvailableColors = "[\"Preto\",\"Cinza\"]",
                            AverageRating = 4.2999999999999998,
                            Brand = "PrintMaster",
                            Category = "Impressoras",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(618),
                            DiscountedPrice = 799.99m,
                            HasPromotion = true,
                            ImageUrl = "ImpressoraColorJetProMultifuncional.jpg",
                            InStock = true,
                            IsBestSeller = false,
                            IsNew = false,
                            Name = "Impressora ColorJet Pro Multifuncional",
                            Price = 899.99m,
                            PromoLabel = "Frete Grátis",
                            ReviewCount = 562
                        },
                        new
                        {
                            Id = 4,
                            AvailableColors = "[\"Prata\",\"Grafite\"]",
                            AverageRating = 4.7999999999999998,
                            Brand = "TechPro",
                            Category = "Notebooks",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(621),
                            DiscountedPrice = 4299.99m,
                            HasPromotion = true,
                            ImageUrl = "notebook1.jpg",
                            InStock = true,
                            IsBestSeller = true,
                            IsNew = false,
                            Name = "Notebook UltraBook X5 Core i7",
                            Price = 4599.99m,
                            PromoLabel = "Cashback 10%",
                            ReviewCount = 1879
                        },
                        new
                        {
                            Id = 5,
                            AvailableColors = "[\"Preto\",\"Azul\",\"Rosa\"]",
                            AvailableSizes = "[\"64GB\",\"128GB\",\"256GB\"]",
                            AverageRating = 4.5,
                            Brand = "GalaxyTech",
                            Category = "Tablets",
                            CreatedAt = new DateTime(2026, 1, 27, 13, 7, 58, 231, DateTimeKind.Utc).AddTicks(623),
                            HasPromotion = false,
                            ImageUrl = "tablet1.jpg",
                            InStock = false,
                            IsBestSeller = false,
                            IsNew = true,
                            Name = "Tablet TabX Pro 10.5\"",
                            Price = 2199.99m,
                            ReviewCount = 892
                        });
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.PromotionEntity", b =>
                {
                    b.Property<string>("PromotionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.AddressEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CartEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CartItemEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.CartEntity", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.OrderEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.CustomerEntity", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.ProductEntity", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.OrderEntity", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.PaymentEntity", b =>
                {
                    b.HasOne("Ciandt.Retail.MCP.Models.Entities.OrderEntity", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Ciandt.Retail.MCP.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
